# Generated by Django 5.0.6 on 2025-04-09 03:18

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_book_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, default=users.models.CustomUser.default_role, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
    ]
