# Generated by Django 5.0.6 on 2025-04-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
