# Generated by Django 5.0.6 on 2025-04-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_borrowslip_created_at_borrowslip_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowslip',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
