# Generated by Django 5.0.6 on 2025-04-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_alter_borrowslip_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowslip',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
